# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: upload release if need

inputs:
    sec_token:  # 定义一个输入参数 cmt_msg
      description: 'secrets.GITHUB_TOKEN'
      required: true
      type: string

runs:
    using: "composite"
    steps:
      - name: Check if Need Upload
        continue-on-error: true
        shell: bash
        id: CheckStep
        # env:
            # 需要使用 GitHub Token 授权 push
            # TTTTTT: '123'
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          if [ -f "data/sqlite_backup.gz.en" ]; then
            echo "需要上传Release"
            echo "UploadRelease=1" >> $GITHUB_OUTPUT
            TAG="auto-$(date +'%Y%m%d%H%M%S')"
            echo "TagName=$TAG" >> $GITHUB_OUTPUT

            Rname="release-$(date +'%Y-%m-%d %H:%M:%S')"
            echo "RName=$Rname" >> $GITHUB_OUTPUT
          else
            echo "无需 Release skip"
            echo "UploadRelease=0" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload release if data/sqlite_backup.gz.en exists
        continue-on-error: true
        if: steps.CheckStep.outputs.UploadRelease == '1'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.CheckStep.outputs.Rname }}
          tag_name: ${{ steps.CheckStep.outputs.TagName }}
          files: data/sqlite_backup.gz.en
          body:  sqlite 数据库文件的备份 (先解密后解压) 密钥:CFGKEY
        env:
          GITHUB_TOKEN: ${{ inputs.sec_token }}

