# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: pushback

inputs:
    cmt_msg:  # 定义一个输入参数 cmt_msg
      description: 'Commit message for the pushback action'
      required: false
      type: string

runs:
    using: "composite"
    steps:
      - name: pushBack
        shell: bash
        env:
            # 需要使用 GitHub Token 授权 push
            TTTTTT: '123'
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
              git status
              echo "msg:${{ inputs.cmt_msg }}"
              git config user.name "github-actions[bot]"
              git config user.email "githubci"
              git status
              git add .
              git diff --cached --quiet || git commit -m "${{inputs.cmt_msg }} [$(date +"%Y-%m-%d %H:%M:%S %Z")] [ci skip]"
              git push origin HEAD:master
