# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
    paths:
      - modifyThisFileToTrigerCI
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '15 */4 * * *'
  

permissions:
  contents: write

jobs:
  

  del_runs:
      needs: RemoveFans
      runs-on: ubuntu-latest
      permissions:
        actions: write
        contents: read
      steps:
        - name: Delete workflow runs for current repo
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 1
            keep_minimum_runs: 5
  RemoveFans:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt --target=./pylib; fi
        ls -al 
    - name: Delete fans and Get History
      continue-on-error: true
      run: |
        python3 -u refreshCookie.py
        python3 -u deleteFans.py
        python3 -u getAllReplies.py 1
      env:
        CFGKEY: '${{ secrets.CFGKEY }}'
    - name: pushBack History
      uses: ./.github/actions/pushback
      with:
        cmt_msg: 'history '

    - name: getAllReplies
      continue-on-error: true
      run: |
        python3 -u getAllReplies.py 2
      env:
        CFGKEY: '${{ secrets.CFGKEY }}'
    - name: pushBack
      uses: ./.github/actions/pushback
      with:
        cmt_msg: 'Get all replies'

    - name: Delete Replies
      continue-on-error: true
      run: |
        date +"%Y-%m-%d %H:%M:%S"
        python3 -u deleteReplies.py
      env:
        CFGKEY: '${{ secrets.CFGKEY }}'
    - name: pushBack
      uses: ./.github/actions/pushback
      with:
        cmt_msg: 'Remove Replies'

     

    
    

    - name: Rename workflow file
      continue-on-error: true
      run: |
        echo "Renaming workflow file to prevent re-triggering"
        mv ./.github/workflows/auto-remove-bilifans.yml ./.github/workflows/auto-remove-bilifans.yml.bak || True
        git add . 
        git commit -m "Rename workflow file to prevent re-triggering" || True

    - name: Sync To codeberg
      uses: Lorem3/push2other@v2.0
      with:
          target-url: ${{ secrets.SYNC_URL1 }}
          private-key: ${{ secrets.SYNC_KEY }}

    - name: Sync To VS
      uses: Lorem3/push2other@v2.0
      with:
          target-url: ${{ secrets.SYNC_URL2 }}
          private-key: ${{ secrets.SYNC_KEY }}
    - name: Sync To G2
      uses: Lorem3/push2other@v2.0
      with:
          target-url: ${{ secrets.SYNC_URL3 }}
          private-key: ${{ secrets.SYNC_KEY }}



    
