# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
    paths:
      - modifyThisFileToTrigerCI
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '10 10 * * *'
  

permissions:
  contents: write

jobs:
  

  del_runs:
      needs: RemoveFans
      runs-on: ubuntu-latest
      permissions:
        actions: write
        contents: read
      steps:
        - name: Delete workflow runs for current repo
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 1
  RemoveFans:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt --target=./pylib; fi
        ls -al 
    - name: Delete
      continue-on-error: true
      run: |
        python3 -u refreshCookie.py
        python3 -u deleteFans.py
        python3 -u getAllReplies.py
        python3 -u deleteReplies.py
      env:
        CFGKEY: '${{ secrets.CFGKEY }}'

    - name: pushBack
      env:
          # 需要使用 GitHub Token 授权 push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
            git config user.name "github-actions[bot]"
            git config user.email "githubci"
            git status
            git add .
            git diff --cached --quiet || git commit -m "[ci skip]"
            git push origin HEAD:master



    
